### ISSUE TITLE
translate: `api/index.md`

### ISSUE THREAD

**Issue by Qocotzxin** [miguelfdezc/vitest-docs-es#40]
Traducir el archivo correspondiente a la ruta: https://vitest.dev/api/

Archivo a traducir: [vitest-dev/vitest:`api/index.md`](https://github.com/vitest-dev/vitest/blob/main/docs/api/index.md)

**Comment by miguelfdezc** [comment]
Issue duplicada, igual que #6 
Por favor, antes de crear nuevas issues revisa las existentes.
Ya hay una issue creada por cada archivo de la documentación original.
