### ISSUE TITLE
translate: config/index.md

### ISSUE THREAD

**Issue by Qocotzxin** [miguelfdezc/vitest-docs-es#41]
Traducir el archivo correspondiente a la ruta: https://vitest.dev/config/

Archivo a traducir: [vitest-dev/vitest:config/index.md](https://github.com/vitest-dev/vitest/blob/main/docs/config/index.md)

**Comment by miguelfdezc** [comment]
Issue duplicada, igual que #7 
Por favor, antes de crear nuevas issues revisa las existentes.
Ya hay una issue creada por cada archivo de la documentación original.
